/**
 * Canvas Document Type Definitions - Backend Abstract Spec v2.0
 *
 * Auto-generated from Pydantic schemas
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * Generated: 2025-11-19 12:08:43
 * Source: app/schemas/canvas.py
 */

// ===================
// Enums
// ===================

export type TextRole =
  | "headline"      // 메인 헤드라인 (50자, 36-72px)
  | "subheadline"   // 서브헤드라인 (100자, 24-48px)
  | "body"          // 본문 텍스트 (14-24px)
  | "caption"       // 캡션/부가설명 (200자, 12-16px)
  | "cta";          // 행동유도 (20자, 16-24px)

export type ShapeType =
  | "rect"
  | "circle"
  | "ellipse"
  | "line"
  | "polygon";

export type FontWeight =
  | "100"  // thin
  | "200"  // extra-light
  | "300"  // light
  | "400"  // normal
  | "500"  // medium
  | "600"  // semi-bold
  | "700"  // bold
  | "800"  // extra-bold
  | "900"; // black

export type TextAlign = "left" | "center" | "right" | "justify";
export type VerticalAlign = "top" | "middle" | "bottom";
export type ObjectType = "text" | "image" | "shape" | "frame" | "group";

export type DocumentKind =
  | "product_detail"
  | "sns_feed"
  | "sns_story"
  | "blog_thumbnail"
  | "ad_banner";

// ===================
// Background Types
// ===================

export interface BackgroundColor {
  type: "color";
  value: string; // Hex color code
}

export interface GradientStop {
  offset: number;  // 0-1
  color: string;   // Hex color code
}

export interface BackgroundGradient {
  type: "gradient";
  gradient_type: "linear" | "radial";
  stops: GradientStop[];
  angle?: number;       // degrees (linear only)
  center_x?: number;    // 0-1 (radial only)
  center_y?: number;    // 0-1 (radial only)
}

export interface BackgroundImage {
  type: "image";
  src: string;  // Image URL
  fit?: "fill" | "contain" | "cover" | "none";
  opacity?: number; // 0-1
}

export type Background = BackgroundColor | BackgroundGradient | BackgroundImage;

// ===================
// Brand Information
// ===================

export interface BrandColors {
  primary: string;           // #RRGGBB
  secondary?: string;        // #RRGGBB
  accent?: string;           // #RRGGBB
  text_primary: string;      // #RRGGBB
  text_secondary: string;    // #RRGGBB
  background: string;        // #RRGGBB
}

export interface BrandFonts {
  primary: string;           // e.g., "Pretendard"
  secondary?: string;        // e.g., "Roboto"
  fallback: string;          // e.g., "sans-serif"
}

export interface BrandLogo {
  url: string;
  width?: number;
  height?: number;
}

export interface BrandInfo {
  colors: BrandColors;
  fonts: BrandFonts;
  logo?: BrandLogo;
}

// ===================
// Canvas Objects
// ===================

export interface BaseObject {
  id: string;
  type: ObjectType;
  x: number;
  y: number;
  width: number;
  height: number;
  rotation?: number;      // degrees, default 0
  opacity?: number;       // 0-1, default 1
  visible?: boolean;      // default true
  locked?: boolean;       // default false
  z_index?: number;       // layer order
}

export interface TextObject extends BaseObject {
  type: "text";
  role: TextRole;
  text: string;

  // Typography
  font_size: number;
  font_family?: string;
  font_weight?: FontWeight;
  line_height?: number;
  letter_spacing?: number;

  // Alignment
  text_align?: TextAlign;
  vertical_align?: VerticalAlign;

  // Colors
  fill: string;           // #RRGGBB
  stroke?: string;        // #RRGGBB
  stroke_width?: number;

  // Effects
  text_decoration?: "underline" | "line-through" | "none";
  text_shadow?: string;   // CSS text-shadow value
}

export interface ImageObject extends BaseObject {
  type: "image";
  role?: string;
  src: string;            // Image URL
  fit?: "fill" | "contain" | "cover" | "none";

  // Effects
  border_radius?: number;
  filters?: string;       // CSS filter value
}

export interface ShapeObject extends BaseObject {
  type: "shape";
  role?: string;
  shape_type: ShapeType;

  // Fill & Stroke
  fill?: string;          // #RRGGBB
  stroke?: string;        // #RRGGBB
  stroke_width?: number;

  // Shape-specific
  border_radius?: number; // rect only
  points?: number[];      // polygon/line [x1,y1,x2,y2,...]
}

export interface FrameObject extends BaseObject {
  type: "frame";
  role?: string;
  background?: Background;
  clip_content?: boolean;
  children: string[];     // Child object IDs
}

export interface GroupObject extends BaseObject {
  type: "group";
  role?: string;
  children: string[];     // Child object IDs
}

export type CanvasObject =
  | TextObject
  | ImageObject
  | ShapeObject
  | FrameObject
  | GroupObject;

// ===================
// Page & Document
// ===================

export interface PagePayload {
  id: string;
  width: number;
  height: number;
  background: Background;
  objects: CanvasObject[];
}

export interface DocumentMetadata {
  title?: string;
  description?: string;
  tags?: string[];
  created_at?: string;    // ISO 8601
  version?: string;
}

export interface DocumentPayload {
  id: string;
  kind: DocumentKind;
  brand: BrandInfo;
  pages: PagePayload[];
  metadata?: DocumentMetadata;
  bindings?: Record<string, string>; // object_path -> data_key
}

// ===================
// API Response
// ===================

export interface CanvasGenerateResponse {
  success: boolean;
  document?: DocumentPayload;
  error?: string;
  metadata?: Record<string, any>;
}

// ===================
// Type Guards
// ===================

export function isTextObject(obj: CanvasObject): obj is TextObject {
  return obj.type === "text";
}

export function isImageObject(obj: CanvasObject): obj is ImageObject {
  return obj.type === "image";
}

export function isShapeObject(obj: CanvasObject): obj is ShapeObject {
  return obj.type === "shape";
}

export function isFrameObject(obj: CanvasObject): obj is FrameObject {
  return obj.type === "frame";
}

export function isGroupObject(obj: CanvasObject): obj is GroupObject {
  return obj.type === "group";
}

// ===================
// Helper Types
// ===================

export interface TextRoleConstraints {
  max_length: number | null;
  min_font_size: number;
  max_font_size: number;
}

export const TEXT_ROLE_CONSTRAINTS: Record<TextRole, TextRoleConstraints> = {
  headline: { max_length: 50, min_font_size: 36, max_font_size: 72 },
  subheadline: { max_length: 100, min_font_size: 24, max_font_size: 48 },
  body: { max_length: null, min_font_size: 14, max_font_size: 24 },
  caption: { max_length: 200, min_font_size: 12, max_font_size: 16 },
  cta: { max_length: 20, min_font_size: 16, max_font_size: 24 },
};
