"""
Nano Banana Provider (Gemini 2.5 Flash Image Generation)

Google AI Studio의 네이티브 이미지 생성 기능

작성일: 2025-11-17
"""
import base64
import logging
from typing import Dict, Any, Optional, Literal
from google import genai
from google.genai import types
from PIL import Image
from io import BytesIO

from .base import MediaProvider, MediaProviderResponse, MediaProviderOutput, ProviderError

logger = logging.getLogger(__name__)


class NanoBananaProvider(MediaProvider):
    """Nano Banana Provider (Gemini Image Generation)"""

    def __init__(
        self,
        api_key: str,
        default_model: str = "gemini-2.5-flash-image",
        timeout: int = 60
    ):
        """
        Args:
            api_key: Google API Key
            default_model: 기본 모델 (gemini-2.5-flash-image)
            timeout: 타임아웃 (초)
        """
        super().__init__(
            vendor="nanobanana",
            base_url="https://generativelanguage.googleapis.com",
            timeout=timeout
        )
        self.client = genai.Client(api_key=api_key)
        self.default_model = default_model

    async def generate(
        self,
        prompt: str,
        task: str,
        media_type: Literal["image", "video", "audio"],
        options: Optional[Dict[str, Any]] = None
    ) -> MediaProviderResponse:
        """
        Gemini Image Generation

        Args:
            prompt: 이미지 생성 프롬프트
            task: 작업 유형 (product_image, brand_logo 등)
            media_type: "image"만 지원
            options: 생성 옵션

        Returns:
            MediaProviderResponse

        Raises:
            ProviderError: 생성 실패 시
        """
        if media_type != "image":
            raise ProviderError(
                message=f"Nano Banana only supports 'image', got '{media_type}'",
                provider=self.vendor,
                status_code=400
            )

        opts = options or {}
        model_name = opts.get("model", self.default_model)
        num_images = opts.get("num_images", 1)
        aspect_ratio = opts.get("aspect_ratio", "1:1")

        logger.info(
            f"[NanoBanana] Generating image: model={model_name}, "
            f"num_images={num_images}, aspect_ratio={aspect_ratio}"
        )

        try:
            # 프롬프트 개선
            enhanced_prompt = self._enhance_prompt(prompt, task)

            # 이미지 생성 설정
            config = types.GenerateContentConfig(
                response_modalities=['Image'],
                image_config=types.ImageConfig(
                    aspect_ratio=aspect_ratio
                )
            )

            # 이미지 생성
            response = self.client.models.generate_content(
                model=model_name,
                contents=[enhanced_prompt],
                config=config
            )

            # 응답에서 이미지 추출
            outputs = []

            # Gemini는 이미지를 response.parts에 반환
            for part in response.parts:
                if part.inline_data is not None:
                    # 이미지 데이터 직접 추출
                    img_bytes = part.inline_data.data

                    # PIL Image로 변환 (크기 정보 얻기 위해)
                    pil_image = Image.open(BytesIO(img_bytes))

                    # Base64로 인코딩
                    img_data = base64.b64encode(img_bytes).decode('utf-8')

                    outputs.append(MediaProviderOutput(
                        type="image",
                        format="png",
                        data=img_data,
                        width=pil_image.width,
                        height=pil_image.height
                    ))

            if not outputs:
                raise ProviderError(
                    message="No images generated by Gemini",
                    provider=self.vendor,
                    status_code=500
                )

            # Usage 정보
            usage = {}
            if hasattr(response, 'usage_metadata'):
                try:
                    usage = {
                        "prompt_tokens": (
                            response.usage_metadata.prompt_token_count
                        ),
                        "completion_tokens": (
                            response.usage_metadata.candidates_token_count
                        ),
                        "total_tokens": (
                            response.usage_metadata.total_token_count
                        )
                    }
                except AttributeError:
                    pass

            logger.info(f"[NanoBanana] Generated {len(outputs)} image(s)")

            return MediaProviderResponse(
                provider=self.vendor,
                model=model_name,
                usage=usage,
                outputs=outputs,
                meta={
                    "task": task,
                    "aspect_ratio": aspect_ratio,
                    "num_images": num_images
                }
            )

        except Exception as e:
            logger.error(f"[NanoBanana] Error: {e}", exc_info=True)
            raise ProviderError(
                message=f"Nano Banana generation failed: {str(e)}",
                provider=self.vendor,
                details={"task": task, "prompt": prompt[:100]}
            )

    async def health_check(self) -> bool:
        """
        Provider 헬스 체크

        Returns:
            True if healthy
        """
        try:
            # 간단한 이미지 생성으로 API 연결 확인
            response = self.client.models.generate_content(
                model=self.default_model,
                contents=["A simple test image"],
                config=types.GenerateContentConfig(
                    response_modalities=['Image']
                )
            )
            return response.parts and len(response.parts) > 0
        except Exception as e:
            logger.error(f"[NanoBanana] Health check failed: {e}")
            return False

    def get_default_options(self, task: str, media_type: str) -> Dict[str, Any]:
        """
        작업 유형별 기본 옵션

        Args:
            task: 작업 유형
            media_type: 미디어 타입

        Returns:
            기본 옵션
        """
        # 작업별 aspect ratio 기본값
        aspect_ratios = {
            "product_image": "1:1",
            "brand_logo": "1:1",
            "sns_thumbnail": "16:9",
            "banner_image": "16:9",
            "story_image": "9:16",
            "profile_image": "1:1"
        }

        return {
            "model": self.default_model,
            "num_images": 1,
            "aspect_ratio": aspect_ratios.get(task, "1:1")
        }

    def _enhance_prompt(self, prompt: str, task: str) -> str:
        """
        프롬프트 개선 (Gemini Image 최적화)

        Args:
            prompt: 원본 프롬프트
            task: 작업 유형

        Returns:
            개선된 프롬프트
        """
        # 작업별 스타일 가이드
        style_guides = {
            "product_image": (
                "high quality product photography, "
                "professional lighting, clean background"
            ),
            "brand_logo": (
                "modern minimalist logo design, "
                "vector style, clean lines"
            ),
            "sns_thumbnail": (
                "eye-catching social media thumbnail, "
                "vibrant colors, engaging composition"
            ),
            "banner_image": (
                "wide banner design, "
                "professional layout, marketing material"
            ),
            "story_image": (
                "vertical story image, "
                "mobile-friendly, attention-grabbing"
            ),
            "profile_image": (
                "professional profile photo, "
                "centered composition, clean background"
            )
        }

        style_guide = style_guides.get(task, "high quality digital art")

        # 최종 프롬프트
        enhanced = f"{prompt}, {style_guide}"

        logger.debug(f"[NanoBanana] Enhanced prompt: {enhanced}")

        return enhanced
