"""Initial tables: users, brands, projects, workflows, agent_logs

Revision ID: 677d1d496d75
Revises: 
Create Date: 2025-11-15 14:49:39.632671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677d1d496d75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('router_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=50), nullable=True),
    sa.Column('selected_agent', sa.String(length=100), nullable=True),
    sa.Column('selected_model', sa.String(length=100), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('context_size_bytes', sa.Integer(), nullable=True),
    sa.Column('decision_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_router_logs_created_at'), 'router_logs', ['created_at'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=50), nullable=False),
    sa.Column('dag_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=True),
    sa.Column('workflow_node_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('source_agent', sa.String(length=100), nullable=True),
    sa.Column('target_agent', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_size_bytes', sa.Integer(), nullable=True),
    sa.Column('log_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_node_id'], ['workflow_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_agent_name'), 'agent_logs', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_logs_created_at'), 'agent_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_logs_request_id'), 'agent_logs', ['request_id'], unique=False)
    op.drop_table('generated_texts')
    op.add_column('brands', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('brands', sa.Column('brand_kit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brands', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('website_url', sa.Text(), nullable=True))
    op.add_column('brands', sa.Column('industry', sa.String(length=100), nullable=True))
    op.add_column('brands', sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('brands', sa.Column('brand_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('brands', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('brands_slug_key', 'brands', type_='unique')
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.drop_constraint('fk_brands_logo_asset', 'brands', type_='foreignkey')
    op.create_foreign_key(None, 'brands', 'users', ['owner_id'], ['id'])
    op.drop_column('brands', 'settings')
    op.drop_column('brands', 'logo_asset_id')
    op.drop_column('brands', 'status')
    op.add_column('generated_assets', sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('idx_generated_assets_brand_created', table_name='generated_assets')
    op.drop_index('idx_generated_assets_checksum', table_name='generated_assets', postgresql_where='(checksum IS NOT NULL)')
    op.drop_index('idx_generated_assets_embedding', table_name='generated_assets', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index('idx_generated_assets_project_created', table_name='generated_assets', postgresql_where='(project_id IS NOT NULL)')
    op.drop_index('idx_generated_assets_tags', table_name='generated_assets', postgresql_using='gin')
    op.drop_index('idx_generated_assets_type_status', table_name='generated_assets')
    op.drop_index('idx_generated_assets_user', table_name='generated_assets')
    op.drop_constraint('generated_assets_project_id_fkey', 'generated_assets', type_='foreignkey')
    op.drop_constraint('generated_assets_user_id_fkey', 'generated_assets', type_='foreignkey')
    op.drop_constraint('generated_assets_brand_id_fkey', 'generated_assets', type_='foreignkey')
    op.drop_column('generated_assets', 'metadata')
    op.add_column('projects', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('project_type', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('project_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('projects_brand_id_slug_key', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.drop_constraint('projects_brand_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'end_date')
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    op.add_column('projects', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_brand_id_fkey', 'projects', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.create_unique_constraint('projects_brand_id_slug_key', 'projects', ['brand_id', 'slug'])
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'tags')
    op.drop_column('projects', 'project_metadata')
    op.drop_column('projects', 'brief')
    op.drop_column('projects', 'project_type')
    op.drop_column('projects', 'owner_id')
    op.add_column('generated_assets', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key('generated_assets_brand_id_fkey', 'generated_assets', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('generated_assets_user_id_fkey', 'generated_assets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('generated_assets_project_id_fkey', 'generated_assets', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_generated_assets_user', 'generated_assets', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_generated_assets_type_status', 'generated_assets', ['type', 'status'], unique=False)
    op.create_index('idx_generated_assets_tags', 'generated_assets', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_generated_assets_project_created', 'generated_assets', ['project_id', sa.text('created_at DESC')], unique=False, postgresql_where='(project_id IS NOT NULL)')
    op.create_index('idx_generated_assets_embedding', 'generated_assets', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_generated_assets_checksum', 'generated_assets', ['checksum'], unique=False, postgresql_where='(checksum IS NOT NULL)')
    op.create_index('idx_generated_assets_brand_created', 'generated_assets', ['brand_id', sa.text('created_at DESC')], unique=False)
    op.drop_column('generated_assets', 'asset_metadata')
    op.add_column('brands', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('logo_asset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.create_foreign_key('fk_brands_logo_asset', 'brands', 'generated_assets', ['logo_asset_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.create_unique_constraint('brands_slug_key', 'brands', ['slug'])
    op.alter_column('brands', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('brands', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('brands', 'deleted_at')
    op.drop_column('brands', 'brand_metadata')
    op.drop_column('brands', 'tags')
    op.drop_column('brands', 'industry')
    op.drop_column('brands', 'website_url')
    op.drop_column('brands', 'logo_url')
    op.drop_column('brands', 'brand_kit')
    op.drop_column('brands', 'owner_id')
    op.create_table('generated_texts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['generated_assets.id'], name='generated_texts_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='generated_texts_pkey')
    )
    op.drop_index(op.f('ix_agent_logs_request_id'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_created_at'), table_name='agent_logs')
    op.drop_index(op.f('ix_agent_logs_agent_name'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_table('workflow_nodes')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_router_logs_created_at'), table_name='router_logs')
    op.drop_table('router_logs')
    # ### end Alembic commands ###
